site_name: Aislan Freitas
plugins:
  - search
  - glightbox
  - blog:
      blog_dir: blog
      post_dir: "{blog}/posts"
      # post_url_date_format: dd/MM/yyyy
      post_url_format: "{date}/{slug}"

nav:
  - Home: 
    - index.md
  - Blog:
    - blog/index.md
  # - Mapeamento das fontes de dados: fonte-dados.md
  # - Roadmap: roadmap.md

theme:
  favicon: assets/images/favicon.svg
  name: material
  icon:
    repo: fontawesome/brands/github
    logo: fontawesome/solid/square-poll-vertical
  palette:
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: octicons/moon-24
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: octicons/sun-24
        name: Switch to light mode
  features:
    - navigation.indexes
    - content.code.copy
  #   - navigation.tabs
  #   - navigation.top
  #   - navegation.expand
  #   - navigation.tabs.sticky
  #   - navigation.tracking
markdown_extensions:
  - footnotes
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences        

extra_javascript:
  - assets/js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/sorts/tablesort.number.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/sorts/tablesort.date.min.js
  - https://unpkg.com/mermaid@8.8.4/dist/mermaid.min.js

extra_css:
  - assets/css/tables.css

# Repository
repo_name: aislansf/site
repo_url: https://github.com/aislansf/site